/**
 * build-awards.js – Generate awards strip image list for the personal site
 *
 * Run after adding images to the awards folder:  node build-awards.js
 *
 * - Scans folder "awards" or "Awards" for image files (.png, .jpg, etc.)
 * - Shuffles the list and writes awards/awards-data.js (window.AWARDS_DATA)
 * - script.js reads that file and fills #activities-track
 */

const fs = require("fs");
const path = require("path");

const EXTS = [".png", ".jpg", ".jpeg", ".webp", ".gif"];

/** Prefer folder that has images; check both "awards" and "Awards" for case differences */
function findAwardsDir() {
  const lower = path.join(__dirname, "awards");
  const upper = path.join(__dirname, "Awards");
  for (const dir of [lower, upper]) {
    try {
      const files = fs.readdirSync(dir);
      const images = files.filter((f) => EXTS.includes(path.extname(f).toLowerCase()));
      if (images.length > 0) return { dir, folderName: path.basename(dir), images };
    } catch (e) {}
  }
  try {
    const dir = path.join(__dirname, "awards");
    fs.mkdirSync(dir, { recursive: true });
    return { dir, folderName: "awards", images: [] };
  } catch (e) {}
  return { dir: __dirname, folderName: "awards", images: [] };
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

const { folderName, images: imageList } = findAwardsDir();
const shuffled = shuffle(imageList);

/* Write list to awards/awards-data.js (same path the HTML script src uses) */
const outDir = path.join(__dirname, "awards");
try {
  fs.mkdirSync(outDir, { recursive: true });
} catch (e) {}
const outFile = path.join(outDir, "awards-data.js");
const data = { folder: folderName, images: shuffled };
const content =
  "// Generated by build-awards.js – add images to the awards folder and run: node build-awards.js\n" +
  "window.AWARDS_DATA = " +
  JSON.stringify(data) +
  ";\n";

try {
  fs.writeFileSync(outFile, content, "utf8");
  console.log("Awards list updated: " + shuffled.length + " image(s) from folder '" + folderName + "'. Refresh the page to see them.");
} catch (e) {
  console.error("Could not write awards-data.js:", e.message);
}
